name: 'private-pypi-github update index.'
description: 'Index all published packages.'
inputs:
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repo'
    required: true
  branch:
    description: 'branch'
    required: false
    default: 'master'
  index_filename:
    description: 'index filename.'
    required: false
    default: 'index.toml'
  github_token:
    description: 'token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'docker://privatepypi/private-pypi:0.1.0a4'
  args:
    - 'update_index'
    - '--type'
    - 'github'
    - '--name'
    - ${{ inputs.repo }}
    - '--secret'
    - ${{ inputs.github_token }}
    - '--owner'
    - ${{ inputs.owner }}
    - '--repo'
    - ${{ inputs.repo }}
    - '--branch'
    - ${{ inputs.branch }}
    - '--index_filename'
    - ${{ inputs.index_filename }}
